# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  # disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About',   url: 'about/'}
#- {name: 'Blog', url: 'blogs.html'}
- {name: 'Projects', url: 'projects/'}
- {name: 'Publications', url: 'publications/'}
#- {name: 'Resume', url: '../assets/resume.pdf'}
#- {name: 'Contact', url: 'contact/'}
#- {name: 'Opensource', url: 'opensource/'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'google',    link: 'https://scholar.google.com/citations?user=IIdc_5gAAAAJ&hl=en'}
- {icon: 'github',     link: 'https://www.github.com/ayanbag'}
- {icon: 'linkedin',   link: 'http://www.linkedin.com/in/ayanbag/'}
- {icon: 'envelope',   link: 'mailto:ayanbag9474@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

# sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'